In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('drug200.csv')


In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    object 
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    object 
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(1), object(4)
memory usage: 9.5+ KB


In [4]:
objList = dataset.select_dtypes(include = "object").columns
print (objList)
objList=objList.delete(1)
objList=objList.delete(2)
print (objList)

Index(['Sex', 'BP', 'Cholesterol', 'Drug'], dtype='object')
Index(['Sex', 'Cholesterol'], dtype='object')


In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for feat in objList:
    dataset[feat] = le.fit_transform(dataset[feat].astype(str))
print (dataset.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Age          200 non-null    int64  
 1   Sex          200 non-null    int64  
 2   BP           200 non-null    object 
 3   Cholesterol  200 non-null    int64  
 4   Na_to_K      200 non-null    float64
 5   Drug         200 non-null    object 
dtypes: float64(1), int64(3), object(2)
memory usage: 9.5+ KB
None


In [6]:

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values


In [7]:
print(X)

[[23 0 'HIGH' 0 25.355]
 [47 1 'LOW' 0 13.093]
 [47 1 'LOW' 0 10.113999999999999]
 [28 0 'NORMAL' 0 7.797999999999999]
 [61 0 'LOW' 0 18.043]
 [22 0 'NORMAL' 0 8.607000000000001]
 [49 0 'NORMAL' 0 16.275]
 [41 1 'LOW' 0 11.037]
 [60 1 'NORMAL' 0 15.171]
 [43 1 'LOW' 1 19.368]
 [47 0 'LOW' 0 11.767000000000001]
 [34 0 'HIGH' 1 19.199]
 [43 1 'LOW' 0 15.376]
 [74 0 'LOW' 0 20.941999999999997]
 [50 0 'NORMAL' 0 12.703]
 [16 0 'HIGH' 1 15.515999999999998]
 [69 1 'LOW' 1 11.455]
 [43 1 'HIGH' 0 13.972000000000001]
 [23 1 'LOW' 0 7.297999999999999]
 [32 0 'HIGH' 1 25.974]
 [57 1 'LOW' 1 19.128]
 [63 1 'NORMAL' 0 25.916999999999998]
 [47 1 'LOW' 1 30.568]
 [48 0 'LOW' 0 15.036]
 [33 0 'LOW' 0 33.486]
 [28 0 'HIGH' 1 18.809]
 [31 1 'HIGH' 0 30.366]
 [49 0 'NORMAL' 1 9.381]
 [39 0 'LOW' 1 22.697]
 [45 1 'LOW' 0 17.951]
 [18 0 'NORMAL' 1 8.75]
 [74 1 'HIGH' 0 9.567]
 [49 1 'LOW' 1 11.014000000000001]
 [65 0 'HIGH' 1 31.875999999999998]
 [53 1 'NORMAL' 0 14.133]
 [46 1 'NORMAL' 1 7.285]
 [32 1 'H

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 0 0 25.355]
 [0.0 1.0 0.0 ... 1 0 13.093]
 [0.0 1.0 0.0 ... 1 0 10.113999999999999]
 ...
 [0.0 0.0 1.0 ... 1 0 9.894]
 [0.0 0.0 1.0 ... 1 1 14.02]
 [0.0 1.0 0.0 ... 0 1 11.349]]


In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [2])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [11]:
print(y)

['DrugY' 'drugC' 'drugC' 'drugX' 'DrugY' 'drugX' 'DrugY' 'drugC' 'DrugY'
 'DrugY' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'drugX' 'drugA'
 'drugC' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'drugX' 'drugB' 'drugX' 'DrugY' 'drugX' 'drugX'
 'drugA' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugB' 'DrugY' 'drugX' 'drugX'
 'drugX' 'drugA' 'drugC' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY'
 'drugB' 'drugC' 'drugB' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'drugA' 'DrugY'
 'drugX' 'drugB' 'DrugY' 'drugA' 'drugX' 'DrugY' 'DrugY' 'drugB' 'DrugY'
 'drugX' 'DrugY' 'DrugY' 'DrugY' 'drugA' 'DrugY' 'drugA' 'drugX' 'drugB'
 'drugX' 'drugC' 'drugA' 'drugC' 'drugB' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'DrugY' 'drugA' 'drugA' 'drugC' 'drugX' 'DrugY' 'drugX' 'drugX' 'DrugY'
 'drugB' 'DrugY' 'drugA' 'drugX' 'drugX' 'drugX' 'drugX' 'DrugY' 'drugX'
 'drugX' 'drugA' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'D

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.tree import DecisionTreeClassifier
regressor= DecisionTreeClassifier(random_state=0)
regressor.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=0, splitter='best')

In [14]:
y_pred = regressor.predict(X_test)

In [15]:
y_pred

array(['drugC', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'drugX', 'drugX',
       'drugX', 'DrugY', 'drugX', 'drugA', 'DrugY', 'DrugY', 'DrugY',
       'drugB', 'drugC', 'DrugY', 'DrugY', 'drugX', 'DrugY', 'DrugY',
       'drugX', 'drugX', 'drugX', 'DrugY', 'DrugY', 'DrugY', 'DrugY',
       'DrugY', 'drugX', 'drugX', 'drugC', 'drugA', 'drugX', 'DrugY',
       'DrugY', 'drugX', 'DrugY', 'drugA', 'drugX'], dtype=object)

In [16]:

print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[['drugC' 'drugC']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['drugX' 'drugX']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['drugA' 'drugA']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugB' 'drugB']
 ['drugC' 'drugC']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['drugX' 'drugX']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['drugX' 'drugX']
 ['drugC' 'drugC']
 ['drugA' 'drugA']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['DrugY' 'DrugY']
 ['drugX' 'drugX']
 ['DrugY' 'DrugY']
 ['drugA' 'drugA']
 ['drugX' 'drugX']]


In [20]:
print(regressor.predict([[23,1,0,1,0,0,1,25.355]]))

['DrugY']
